#!/usr/bin/env bash
# ============================================================
# 客户端一键接入脚本
# 把本机的 DNS（可选连同默认网关）指向指定的 DNS 服务器。
#
# 两种模式:
#   默认（软强制）    —— 只改 DNS 解析器，移除原有公共 DNS(8.8.8.8 等)
#   --gateway（硬强制）—— 额外把默认网关改到 DNS 服务器，
#                        配合服务端劫持，即使写死 8.8.8.8 也会被强制走本机 DNS
#
# 用法:
#   sudo ./client-setup.sh <DNS服务器IP>                 # 软强制
#   sudo ./client-setup.sh <DNS服务器IP> --gateway       # 硬强制
#   sudo ./client-setup.sh 10.0.0.5 10.0.0.6             # 主备 DNS
# ============================================================
set -euo pipefail

G='\033[0;32m'; Y='\033[1;33m'; R='\033[0;31m'; C='\033[0;36m'; B='\033[1m'; N='\033[0m'
log_info(){ echo -e "${G}[INFO]${N} $*" >&2; }
log_warn(){ echo -e "${Y}[WARN]${N} $*" >&2; }
log_error(){ echo -e "${R}[ERROR]${N} $*" >&2; }
log_ok(){ echo -e "${G}[ OK ]${N} $*" >&2; }
die(){ log_error "$*"; exit 1; }

[[ ${EUID} -eq 0 ]] || die "请用 root 或 sudo 运行"

USE_GATEWAY=0
DNS_IPS=()
for arg in "$@"; do
    case "${arg}" in
        --gateway|-g) USE_GATEWAY=1 ;;
        --help|-h)
            echo "用法: sudo $0 <DNS服务器IP> [备用IP ...] [--gateway]"
            exit 0
            ;;
        *) DNS_IPS+=("${arg}") ;;
    esac
done

[[ ${#DNS_IPS[@]} -ge 1 ]] || die "用法: sudo $0 <DNS服务器IP> [备用IP ...] [--gateway]"

for ip in "${DNS_IPS[@]}"; do
    [[ "${ip}" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || die "无效 IPv4 地址: ${ip}"
done

PRIMARY_DNS="${DNS_IPS[0]}"
log_info "DNS 服务器: ${DNS_IPS[*]}"
[[ ${USE_GATEWAY} -eq 1 ]] && log_info "模式: 硬强制（同时修改默认网关 -> ${PRIMARY_DNS}）" \
                            || log_info "模式: 软强制（仅修改 DNS）"

# ---------- 设置 DNS ----------
set_dns_resolved(){
    log_info "检测到 systemd-resolved，写入 resolved 配置"
    mkdir -p /etc/systemd/resolved.conf.d
    cat > /etc/systemd/resolved.conf.d/dns-custom.conf <<EOF
[Resolve]
DNS=$(IFS=' '; echo "${DNS_IPS[*]}")
Domains=~.
DNSSEC=no
EOF
    systemctl restart systemd-resolved
    if [[ -f /run/systemd/resolve/resolv.conf ]]; then
        ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf 2>/dev/null || true
    elif [[ -f /run/systemd/resolve/stub-resolv.conf ]]; then
        ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf 2>/dev/null || true
    fi
    log_ok "已通过 systemd-resolved 设置 DNS"
}

set_dns_resolvconf(){
    log_info "直接写 /etc/resolv.conf"
    [[ -f /etc/resolv.conf && ! -L /etc/resolv.conf ]] && \
        cp -a /etc/resolv.conf "/etc/resolv.conf.bak.$(date +%F_%H%M%S)" 2>/dev/null || true
    local tmp
    tmp=$(mktemp)
    {
        echo "# Generated by client-setup.sh — 仅使用指定 DNS 服务器"
        for ip in "${DNS_IPS[@]}"; do echo "nameserver ${ip}"; done
        # 保留原有 options/search/domain，去掉旧 nameserver 与注释
        [[ -f /etc/resolv.conf ]] && grep -vE '^[[:space:]]*(nameserver|#|$)' /etc/resolv.conf 2>/dev/null || true
    } > "${tmp}"
    [[ -L /etc/resolv.conf ]] && rm -f /etc/resolv.conf
    mv "${tmp}" /etc/resolv.conf
    chmod 644 /etc/resolv.conf
    log_ok "已写入 /etc/resolv.conf"
}

if command -v systemctl >/dev/null 2>&1 && systemctl is-active --quiet systemd-resolved 2>/dev/null; then
    set_dns_resolved
else
    set_dns_resolvconf
fi

# NetworkManager 接管时写入连接，避免被覆盖
if command -v nmcli >/dev/null 2>&1 && systemctl is-active --quiet NetworkManager 2>/dev/null; then
    conn=$(nmcli -t -f NAME connection show --active 2>/dev/null | head -1)
    if [[ -n "${conn}" ]]; then
        nmcli con mod "${conn}" ipv4.dns "$(IFS=' '; echo "${DNS_IPS[*]}")" ipv4.ignore-auto-dns yes 2>/dev/null || true
        nmcli con mod "${conn}" ipv6.dns "" ipv6.ignore-auto-dns yes 2>/dev/null || true
        nmcli con up "${conn}" >/dev/null 2>&1 || true
        log_ok "NetworkManager 已更新连接: ${conn}"
    fi
fi

# ---------- 设置默认网关（硬强制） ----------
if [[ ${USE_GATEWAY} -eq 1 ]]; then
    log_warn "即将把默认网关改为 ${PRIMARY_DNS}"
    log_warn "请确认 ${PRIMARY_DNS} 已开启 IP 转发与 NAT，否则本机将断网！"
    old_gw=$(ip route 2>/dev/null | awk '/^default/ {print $3; exit}')
    [[ -n "${old_gw}" ]] && log_info "原默认网关: ${old_gw}（如需回滚: sudo ip route replace default via ${old_gw}）"
    if ip route replace default via "${PRIMARY_DNS}" 2>/dev/null; then
        log_ok "默认网关已改为 ${PRIMARY_DNS}"
    else
        log_error "设置默认网关失败，请手动执行: ip route replace default via ${PRIMARY_DNS}"
    fi
fi

# ---------- 验证 ----------
echo "" >&2
log_info "当前生效的 nameserver:"
if command -v resolvectl >/dev/null 2>&1; then
    resolvectl status 2>/dev/null | grep -iE 'DNS Servers|Current DNS' >&2 || true
fi
grep -E '^[[:space:]]*nameserver' /etc/resolv.conf 2>/dev/null >&2 || true

echo "" >&2
log_info "测试解析 example.com ..."
ok=0
for ip in "${DNS_IPS[@]}"; do
    if command -v dig >/dev/null 2>&1; then
        if dig @"${ip}" +short +time=3 +tries=1 example.com A >/dev/null 2>&1; then
            log_ok "OK via ${ip}"
            ok=1; break
        fi
    fi
done
if [[ ${ok} -eq 0 ]]; then
    if command -v dig >/dev/null 2>&1; then
        dig +short +time=3 +tries=1 example.com A >/dev/null 2>&1 && { log_ok "OK (系统解析器)"; ok=1; }
    elif command -v getent >/dev/null 2>&1; then
        getent hosts example.com >/dev/null 2>&1 && { log_ok "OK"; ok=1; }
    fi
fi
[[ ${ok} -eq 0 ]] && log_warn "解析测试未通过：请检查 DNS 服务器可达性、ALLOW_NETS 与防火墙/安全组(UDP 53)"

echo "" >&2
log_ok "客户端接入完成"
